[package]
name = "colortest-cargo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
strip = true
panic = "abort"
opt-level = 3
lto = true
debug = false
codegen-units = 1
